### ISSUE TITLE
return list of applications based on selected timeframe

### ISSUE THREAD

**Issue by shini4i** [shini4i/argo-watcher#148]
We are returning the complete list of available applications even if these applications were not deployed within the selected timeframe. It is misleading. Let's change it.

**Comment by bozerkins** [comment]
There are two ways we can implement it. There's a proper way and a hacky way. Since we're planning long term for a proper HA mode and reliable UI, I would go with the first option. @shini4i , @tomsozolins would like to hear your input regarding this.

### Option 1 (proper)
#### Backend changes
We change the tasks API so that it not only has application and timeframe filters, but limit as well. We'll do a backend-based pagination, meaning on every page change we'll be fetching records for that page from the backend.
For the API  that returns applications, we would need to introduce timeframe filters. 
#### Frontend change
In Frontend, we'll be doing a query to a database for a proper page on every page change (or filters change).
For the Application filter, we'll do a reload of the list of applications when the timeframe filter changes.

### Option 2 (hacky)
Since we're currently loading all the tasks for all the pages in the timeframe, we can fetch distinct applications from the tasks that we receive. It's a very easy way to get the functionality right now, but this would also make the UI page very slow if we have a bigger timeframe and hundreds of deployments daily (thousands of records to render per page).
