### ISSUE TITLE
add redeploy button to ui

### ISSUE THREAD

**Issue by shini4i** [shini4i/argo-watcher#175]
As we transition to managing deployments via argo-watcher, it might be beneficial to introduce a "Redeploy" button on the task details page. This would streamline the rollback process.

This feature will require some authorization on the front-end side. What do you think, @bozerkins?

**Comment by bozerkins** [comment]
It would be great to have this feature. I agree, we'd need UI authorization for this to be a safe feature. 
As a PoC, we can implement simple authorization and `VIEWER` / `ADMIN` roles? So that certain people could only view the deployments, and others could do redeploy (or rollback?).

The proper feature list should include:
1. Authentication, authorization through SAML / LDAP / OpenID Connect
2. We should control which user has access to deploy which project, by having project groups
3. Client tokens should also be tied into this authentication system, so that we can trigger project deployment only with a properly set token (project tokens?)

I might be missing something, but I'd want to implement core security features before adding this functionality. 

Alternatively, we can add this feature under a configuration, so that argo-watcher admins could enable / disable redeploy in UI (at their own risk), and then we plan the security improvements for the future :D

**Comment by shini4i** [comment]
We had a short internal discussion. Regarding permissions scope, we can take the existing group/user mapping from ArgoCD. This way, we won't need to duplicate the configuration.

Of course, regarding the "Redeploy" button, we will have to make some tweaks as we won't have as many potential permissions.
